# Generated by Django 4.0.1 on 2022-01-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classifiedTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=100)),
                ('tweet', models.CharField(max_length=300)),
                ('sentiment', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='classifiedTweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=100)),
                ('tweet', models.CharField(max_length=500)),
                ('sentiment', models.CharField(max_length=50)),
            ],
        ),
    ]
