# Generated by Django 4.0.1 on 2022-01-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedtweet',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
